server:
  port: 8080
  servlet:
    context-path: /api
spring:
  main:
    banner-mode: off
  application:
    name: cola-ddd-scaffold
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
